// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/preference.proto

package preferencepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Preference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mood          string                 `protobuf:"bytes,3,opt,name=mood,proto3" json:"mood,omitempty"`
	Budget        int32                  `protobuf:"varint,4,opt,name=budget,proto3" json:"budget,omitempty"`
	Duration      int32                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	TravelDate    string                 `protobuf:"bytes,7,opt,name=travel_date,json=travelDate,proto3" json:"travel_date,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Preference) Reset() {
	*x = Preference{}
	mi := &file_proto_preference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Preference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Preference) ProtoMessage() {}

func (x *Preference) ProtoReflect() protoreflect.Message {
	mi := &file_proto_preference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Preference.ProtoReflect.Descriptor instead.
func (*Preference) Descriptor() ([]byte, []int) {
	return file_proto_preference_proto_rawDescGZIP(), []int{0}
}

func (x *Preference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Preference) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Preference) GetMood() string {
	if x != nil {
		return x.Mood
	}
	return ""
}

func (x *Preference) GetBudget() int32 {
	if x != nil {
		return x.Budget
	}
	return 0
}

func (x *Preference) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Preference) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Preference) GetTravelDate() string {
	if x != nil {
		return x.TravelDate
	}
	return ""
}

func (x *Preference) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreatePreferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mood          string                 `protobuf:"bytes,2,opt,name=mood,proto3" json:"mood,omitempty"`
	Budget        int32                  `protobuf:"varint,3,opt,name=budget,proto3" json:"budget,omitempty"`
	Duration      int32                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	TravelDate    string                 `protobuf:"bytes,6,opt,name=travel_date,json=travelDate,proto3" json:"travel_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePreferenceRequest) Reset() {
	*x = CreatePreferenceRequest{}
	mi := &file_proto_preference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePreferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePreferenceRequest) ProtoMessage() {}

func (x *CreatePreferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_preference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePreferenceRequest.ProtoReflect.Descriptor instead.
func (*CreatePreferenceRequest) Descriptor() ([]byte, []int) {
	return file_proto_preference_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePreferenceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePreferenceRequest) GetMood() string {
	if x != nil {
		return x.Mood
	}
	return ""
}

func (x *CreatePreferenceRequest) GetBudget() int32 {
	if x != nil {
		return x.Budget
	}
	return 0
}

func (x *CreatePreferenceRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CreatePreferenceRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreatePreferenceRequest) GetTravelDate() string {
	if x != nil {
		return x.TravelDate
	}
	return ""
}

type UpdatePreferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mood          string                 `protobuf:"bytes,3,opt,name=mood,proto3" json:"mood,omitempty"`
	Budget        int32                  `protobuf:"varint,4,opt,name=budget,proto3" json:"budget,omitempty"`
	Duration      int32                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	TravelDate    string                 `protobuf:"bytes,7,opt,name=travel_date,json=travelDate,proto3" json:"travel_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePreferenceRequest) Reset() {
	*x = UpdatePreferenceRequest{}
	mi := &file_proto_preference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferenceRequest) ProtoMessage() {}

func (x *UpdatePreferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_preference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferenceRequest.ProtoReflect.Descriptor instead.
func (*UpdatePreferenceRequest) Descriptor() ([]byte, []int) {
	return file_proto_preference_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePreferenceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePreferenceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePreferenceRequest) GetMood() string {
	if x != nil {
		return x.Mood
	}
	return ""
}

func (x *UpdatePreferenceRequest) GetBudget() int32 {
	if x != nil {
		return x.Budget
	}
	return 0
}

func (x *UpdatePreferenceRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *UpdatePreferenceRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdatePreferenceRequest) GetTravelDate() string {
	if x != nil {
		return x.TravelDate
	}
	return ""
}

type GetPreferenceHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferenceHistoryRequest) Reset() {
	*x = GetPreferenceHistoryRequest{}
	mi := &file_proto_preference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferenceHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferenceHistoryRequest) ProtoMessage() {}

func (x *GetPreferenceHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_preference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferenceHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetPreferenceHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_preference_proto_rawDescGZIP(), []int{3}
}

func (x *GetPreferenceHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeletePreferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePreferenceRequest) Reset() {
	*x = DeletePreferenceRequest{}
	mi := &file_proto_preference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePreferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePreferenceRequest) ProtoMessage() {}

func (x *DeletePreferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_preference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePreferenceRequest.ProtoReflect.Descriptor instead.
func (*DeletePreferenceRequest) Descriptor() ([]byte, []int) {
	return file_proto_preference_proto_rawDescGZIP(), []int{4}
}

func (x *DeletePreferenceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeletePreferenceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PreferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preference    *Preference            `protobuf:"bytes,1,opt,name=preference,proto3" json:"preference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreferenceResponse) Reset() {
	*x = PreferenceResponse{}
	mi := &file_proto_preference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreferenceResponse) ProtoMessage() {}

func (x *PreferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_preference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreferenceResponse.ProtoReflect.Descriptor instead.
func (*PreferenceResponse) Descriptor() ([]byte, []int) {
	return file_proto_preference_proto_rawDescGZIP(), []int{5}
}

func (x *PreferenceResponse) GetPreference() *Preference {
	if x != nil {
		return x.Preference
	}
	return nil
}

type PreferenceHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preferences   []*Preference          `protobuf:"bytes,1,rep,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreferenceHistoryResponse) Reset() {
	*x = PreferenceHistoryResponse{}
	mi := &file_proto_preference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreferenceHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreferenceHistoryResponse) ProtoMessage() {}

func (x *PreferenceHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_preference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreferenceHistoryResponse.ProtoReflect.Descriptor instead.
func (*PreferenceHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_preference_proto_rawDescGZIP(), []int{6}
}

func (x *PreferenceHistoryResponse) GetPreferences() []*Preference {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type DeletePreferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePreferenceResponse) Reset() {
	*x = DeletePreferenceResponse{}
	mi := &file_proto_preference_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePreferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePreferenceResponse) ProtoMessage() {}

func (x *DeletePreferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_preference_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePreferenceResponse.ProtoReflect.Descriptor instead.
func (*DeletePreferenceResponse) Descriptor() ([]byte, []int) {
	return file_proto_preference_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePreferenceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_preference_proto protoreflect.FileDescriptor

const file_proto_preference_proto_rawDesc = "" +
	"\n" +
	"\x16proto/preference.proto\x12\n" +
	"preference\"\xd9\x01\n" +
	"\n" +
	"Preference\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04mood\x18\x03 \x01(\tR\x04mood\x12\x16\n" +
	"\x06budget\x18\x04 \x01(\x05R\x06budget\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x05R\bduration\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12\x1f\n" +
	"\vtravel_date\x18\a \x01(\tR\n" +
	"travelDate\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"\xb7\x01\n" +
	"\x17CreatePreferenceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04mood\x18\x02 \x01(\tR\x04mood\x12\x16\n" +
	"\x06budget\x18\x03 \x01(\x05R\x06budget\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x05R\bduration\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x1f\n" +
	"\vtravel_date\x18\x06 \x01(\tR\n" +
	"travelDate\"\xc7\x01\n" +
	"\x17UpdatePreferenceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04mood\x18\x03 \x01(\tR\x04mood\x12\x16\n" +
	"\x06budget\x18\x04 \x01(\x05R\x06budget\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x05R\bduration\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12\x1f\n" +
	"\vtravel_date\x18\a \x01(\tR\n" +
	"travelDate\"6\n" +
	"\x1bGetPreferenceHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"B\n" +
	"\x17DeletePreferenceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"L\n" +
	"\x12PreferenceResponse\x126\n" +
	"\n" +
	"preference\x18\x01 \x01(\v2\x16.preference.PreferenceR\n" +
	"preference\"U\n" +
	"\x19PreferenceHistoryResponse\x128\n" +
	"\vpreferences\x18\x01 \x03(\v2\x16.preference.PreferenceR\vpreferences\"4\n" +
	"\x18DeletePreferenceResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x8c\x03\n" +
	"\x11PreferenceService\x12W\n" +
	"\x10CreatePreference\x12#.preference.CreatePreferenceRequest\x1a\x1e.preference.PreferenceResponse\x12f\n" +
	"\x14GetPreferenceHistory\x12'.preference.GetPreferenceHistoryRequest\x1a%.preference.PreferenceHistoryResponse\x12W\n" +
	"\x10UpdatePreference\x12#.preference.UpdatePreferenceRequest\x1a\x1e.preference.PreferenceResponse\x12]\n" +
	"\x10DeletePreference\x12#.preference.DeletePreferenceRequest\x1a$.preference.DeletePreferenceResponseB\x16Z\x14./proto/preferencepbb\x06proto3"

var (
	file_proto_preference_proto_rawDescOnce sync.Once
	file_proto_preference_proto_rawDescData []byte
)

func file_proto_preference_proto_rawDescGZIP() []byte {
	file_proto_preference_proto_rawDescOnce.Do(func() {
		file_proto_preference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_preference_proto_rawDesc), len(file_proto_preference_proto_rawDesc)))
	})
	return file_proto_preference_proto_rawDescData
}

var file_proto_preference_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_preference_proto_goTypes = []any{
	(*Preference)(nil),                  // 0: preference.Preference
	(*CreatePreferenceRequest)(nil),     // 1: preference.CreatePreferenceRequest
	(*UpdatePreferenceRequest)(nil),     // 2: preference.UpdatePreferenceRequest
	(*GetPreferenceHistoryRequest)(nil), // 3: preference.GetPreferenceHistoryRequest
	(*DeletePreferenceRequest)(nil),     // 4: preference.DeletePreferenceRequest
	(*PreferenceResponse)(nil),          // 5: preference.PreferenceResponse
	(*PreferenceHistoryResponse)(nil),   // 6: preference.PreferenceHistoryResponse
	(*DeletePreferenceResponse)(nil),    // 7: preference.DeletePreferenceResponse
}
var file_proto_preference_proto_depIdxs = []int32{
	0, // 0: preference.PreferenceResponse.preference:type_name -> preference.Preference
	0, // 1: preference.PreferenceHistoryResponse.preferences:type_name -> preference.Preference
	1, // 2: preference.PreferenceService.CreatePreference:input_type -> preference.CreatePreferenceRequest
	3, // 3: preference.PreferenceService.GetPreferenceHistory:input_type -> preference.GetPreferenceHistoryRequest
	2, // 4: preference.PreferenceService.UpdatePreference:input_type -> preference.UpdatePreferenceRequest
	4, // 5: preference.PreferenceService.DeletePreference:input_type -> preference.DeletePreferenceRequest
	5, // 6: preference.PreferenceService.CreatePreference:output_type -> preference.PreferenceResponse
	6, // 7: preference.PreferenceService.GetPreferenceHistory:output_type -> preference.PreferenceHistoryResponse
	5, // 8: preference.PreferenceService.UpdatePreference:output_type -> preference.PreferenceResponse
	7, // 9: preference.PreferenceService.DeletePreference:output_type -> preference.DeletePreferenceResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_preference_proto_init() }
func file_proto_preference_proto_init() {
	if File_proto_preference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_preference_proto_rawDesc), len(file_proto_preference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_preference_proto_goTypes,
		DependencyIndexes: file_proto_preference_proto_depIdxs,
		MessageInfos:      file_proto_preference_proto_msgTypes,
	}.Build()
	File_proto_preference_proto = out.File
	file_proto_preference_proto_goTypes = nil
	file_proto_preference_proto_depIdxs = nil
}
