// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/preference.proto

package preferencepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PreferenceService_CreatePreference_FullMethodName     = "/preference.PreferenceService/CreatePreference"
	PreferenceService_GetPreferenceHistory_FullMethodName = "/preference.PreferenceService/GetPreferenceHistory"
	PreferenceService_UpdatePreference_FullMethodName     = "/preference.PreferenceService/UpdatePreference"
	PreferenceService_DeletePreference_FullMethodName     = "/preference.PreferenceService/DeletePreference"
)

// PreferenceServiceClient is the client API for PreferenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PreferenceServiceClient interface {
	CreatePreference(ctx context.Context, in *CreatePreferenceRequest, opts ...grpc.CallOption) (*PreferenceResponse, error)
	GetPreferenceHistory(ctx context.Context, in *GetPreferenceHistoryRequest, opts ...grpc.CallOption) (*PreferenceHistoryResponse, error)
	UpdatePreference(ctx context.Context, in *UpdatePreferenceRequest, opts ...grpc.CallOption) (*PreferenceResponse, error)
	DeletePreference(ctx context.Context, in *DeletePreferenceRequest, opts ...grpc.CallOption) (*DeletePreferenceResponse, error)
}

type preferenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPreferenceServiceClient(cc grpc.ClientConnInterface) PreferenceServiceClient {
	return &preferenceServiceClient{cc}
}

func (c *preferenceServiceClient) CreatePreference(ctx context.Context, in *CreatePreferenceRequest, opts ...grpc.CallOption) (*PreferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreferenceResponse)
	err := c.cc.Invoke(ctx, PreferenceService_CreatePreference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *preferenceServiceClient) GetPreferenceHistory(ctx context.Context, in *GetPreferenceHistoryRequest, opts ...grpc.CallOption) (*PreferenceHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreferenceHistoryResponse)
	err := c.cc.Invoke(ctx, PreferenceService_GetPreferenceHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *preferenceServiceClient) UpdatePreference(ctx context.Context, in *UpdatePreferenceRequest, opts ...grpc.CallOption) (*PreferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreferenceResponse)
	err := c.cc.Invoke(ctx, PreferenceService_UpdatePreference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *preferenceServiceClient) DeletePreference(ctx context.Context, in *DeletePreferenceRequest, opts ...grpc.CallOption) (*DeletePreferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePreferenceResponse)
	err := c.cc.Invoke(ctx, PreferenceService_DeletePreference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PreferenceServiceServer is the server API for PreferenceService service.
// All implementations must embed UnimplementedPreferenceServiceServer
// for forward compatibility.
type PreferenceServiceServer interface {
	CreatePreference(context.Context, *CreatePreferenceRequest) (*PreferenceResponse, error)
	GetPreferenceHistory(context.Context, *GetPreferenceHistoryRequest) (*PreferenceHistoryResponse, error)
	UpdatePreference(context.Context, *UpdatePreferenceRequest) (*PreferenceResponse, error)
	DeletePreference(context.Context, *DeletePreferenceRequest) (*DeletePreferenceResponse, error)
	mustEmbedUnimplementedPreferenceServiceServer()
}

// UnimplementedPreferenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPreferenceServiceServer struct{}

func (UnimplementedPreferenceServiceServer) CreatePreference(context.Context, *CreatePreferenceRequest) (*PreferenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePreference not implemented")
}
func (UnimplementedPreferenceServiceServer) GetPreferenceHistory(context.Context, *GetPreferenceHistoryRequest) (*PreferenceHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPreferenceHistory not implemented")
}
func (UnimplementedPreferenceServiceServer) UpdatePreference(context.Context, *UpdatePreferenceRequest) (*PreferenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePreference not implemented")
}
func (UnimplementedPreferenceServiceServer) DeletePreference(context.Context, *DeletePreferenceRequest) (*DeletePreferenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePreference not implemented")
}
func (UnimplementedPreferenceServiceServer) mustEmbedUnimplementedPreferenceServiceServer() {}
func (UnimplementedPreferenceServiceServer) testEmbeddedByValue()                           {}

// UnsafePreferenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PreferenceServiceServer will
// result in compilation errors.
type UnsafePreferenceServiceServer interface {
	mustEmbedUnimplementedPreferenceServiceServer()
}

func RegisterPreferenceServiceServer(s grpc.ServiceRegistrar, srv PreferenceServiceServer) {
	// If the following call panics, it indicates UnimplementedPreferenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PreferenceService_ServiceDesc, srv)
}

func _PreferenceService_CreatePreference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePreferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreferenceServiceServer).CreatePreference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreferenceService_CreatePreference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreferenceServiceServer).CreatePreference(ctx, req.(*CreatePreferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PreferenceService_GetPreferenceHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPreferenceHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreferenceServiceServer).GetPreferenceHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreferenceService_GetPreferenceHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreferenceServiceServer).GetPreferenceHistory(ctx, req.(*GetPreferenceHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PreferenceService_UpdatePreference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePreferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreferenceServiceServer).UpdatePreference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreferenceService_UpdatePreference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreferenceServiceServer).UpdatePreference(ctx, req.(*UpdatePreferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PreferenceService_DeletePreference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePreferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreferenceServiceServer).DeletePreference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreferenceService_DeletePreference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreferenceServiceServer).DeletePreference(ctx, req.(*DeletePreferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PreferenceService_ServiceDesc is the grpc.ServiceDesc for PreferenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PreferenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "preference.PreferenceService",
	HandlerType: (*PreferenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePreference",
			Handler:    _PreferenceService_CreatePreference_Handler,
		},
		{
			MethodName: "GetPreferenceHistory",
			Handler:    _PreferenceService_GetPreferenceHistory_Handler,
		},
		{
			MethodName: "UpdatePreference",
			Handler:    _PreferenceService_UpdatePreference_Handler,
		},
		{
			MethodName: "DeletePreference",
			Handler:    _PreferenceService_DeletePreference_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/preference.proto",
}
