// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/location.proto

package locationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindLocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mood          string                 `protobuf:"bytes,1,opt,name=mood,proto3" json:"mood,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Budget        float64                `protobuf:"fixed64,3,opt,name=budget,proto3" json:"budget,omitempty"`
	Duration      int32                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindLocationsRequest) Reset() {
	*x = FindLocationsRequest{}
	mi := &file_proto_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindLocationsRequest) ProtoMessage() {}

func (x *FindLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindLocationsRequest.ProtoReflect.Descriptor instead.
func (*FindLocationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{0}
}

func (x *FindLocationsRequest) GetMood() string {
	if x != nil {
		return x.Mood
	}
	return ""
}

func (x *FindLocationsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *FindLocationsRequest) GetBudget() float64 {
	if x != nil {
		return x.Budget
	}
	return 0
}

func (x *FindLocationsRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *FindLocationsRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaceId       string                 `protobuf:"bytes,1,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Lat           float64                `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,5,opt,name=lon,proto3" json:"lon,omitempty"`
	Mood          string                 `protobuf:"bytes,6,opt,name=mood,proto3" json:"mood,omitempty"`
	City          string                 `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_proto_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{1}
}

func (x *Location) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

func (x *Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Location) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Location) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Location) GetMood() string {
	if x != nil {
		return x.Mood
	}
	return ""
}

func (x *Location) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type FindLocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*Location            `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindLocationsResponse) Reset() {
	*x = FindLocationsResponse{}
	mi := &file_proto_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindLocationsResponse) ProtoMessage() {}

func (x *FindLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindLocationsResponse.ProtoReflect.Descriptor instead.
func (*FindLocationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{2}
}

func (x *FindLocationsResponse) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

type GetLocationDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaceId       string                 `protobuf:"bytes,1,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationDetailsRequest) Reset() {
	*x = GetLocationDetailsRequest{}
	mi := &file_proto_location_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationDetailsRequest) ProtoMessage() {}

func (x *GetLocationDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetLocationDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{3}
}

func (x *GetLocationDetailsRequest) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

type LocationDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaceId       string                 `protobuf:"bytes,1,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Website       string                 `protobuf:"bytes,4,opt,name=website,proto3" json:"website,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	OpeningHours  string                 `protobuf:"bytes,6,opt,name=opening_hours,json=openingHours,proto3" json:"opening_hours,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationDetailsResponse) Reset() {
	*x = LocationDetailsResponse{}
	mi := &file_proto_location_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationDetailsResponse) ProtoMessage() {}

func (x *LocationDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationDetailsResponse.ProtoReflect.Descriptor instead.
func (*LocationDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{4}
}

func (x *LocationDetailsResponse) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

func (x *LocationDetailsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LocationDetailsResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *LocationDetailsResponse) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *LocationDetailsResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LocationDetailsResponse) GetOpeningHours() string {
	if x != nil {
		return x.OpeningHours
	}
	return ""
}

func (x *LocationDetailsResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_proto_location_proto protoreflect.FileDescriptor

const file_proto_location_proto_rawDesc = "" +
	"\n" +
	"\x14proto/location.proto\x12\blocation\"\x8e\x01\n" +
	"\x14FindLocationsRequest\x12\x12\n" +
	"\x04mood\x18\x01 \x01(\tR\x04mood\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x16\n" +
	"\x06budget\x18\x03 \x01(\x01R\x06budget\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x05R\bduration\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\"\x99\x01\n" +
	"\bLocation\x12\x19\n" +
	"\bplace_id\x18\x01 \x01(\tR\aplaceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x10\n" +
	"\x03lat\x18\x04 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x05 \x01(\x01R\x03lon\x12\x12\n" +
	"\x04mood\x18\x06 \x01(\tR\x04mood\x12\x12\n" +
	"\x04city\x18\a \x01(\tR\x04city\"I\n" +
	"\x15FindLocationsResponse\x120\n" +
	"\tlocations\x18\x01 \x03(\v2\x12.location.LocationR\tlocations\"6\n" +
	"\x19GetLocationDetailsRequest\x12\x19\n" +
	"\bplace_id\x18\x01 \x01(\tR\aplaceId\"\xd9\x01\n" +
	"\x17LocationDetailsResponse\x12\x19\n" +
	"\bplace_id\x18\x01 \x01(\tR\aplaceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x18\n" +
	"\awebsite\x18\x04 \x01(\tR\awebsite\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12#\n" +
	"\ropening_hours\x18\x06 \x01(\tR\fopeningHours\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription2\xc9\x01\n" +
	"\x0fLocationService\x12X\n" +
	"\x15FindSuitableLocations\x12\x1e.location.FindLocationsRequest\x1a\x1f.location.FindLocationsResponse\x12\\\n" +
	"\x12GetLocationDetails\x12#.location.GetLocationDetailsRequest\x1a!.location.LocationDetailsResponseB\x14Z\x12./proto/locationpbb\x06proto3"

var (
	file_proto_location_proto_rawDescOnce sync.Once
	file_proto_location_proto_rawDescData []byte
)

func file_proto_location_proto_rawDescGZIP() []byte {
	file_proto_location_proto_rawDescOnce.Do(func() {
		file_proto_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_location_proto_rawDesc), len(file_proto_location_proto_rawDesc)))
	})
	return file_proto_location_proto_rawDescData
}

var file_proto_location_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_location_proto_goTypes = []any{
	(*FindLocationsRequest)(nil),      // 0: location.FindLocationsRequest
	(*Location)(nil),                  // 1: location.Location
	(*FindLocationsResponse)(nil),     // 2: location.FindLocationsResponse
	(*GetLocationDetailsRequest)(nil), // 3: location.GetLocationDetailsRequest
	(*LocationDetailsResponse)(nil),   // 4: location.LocationDetailsResponse
}
var file_proto_location_proto_depIdxs = []int32{
	1, // 0: location.FindLocationsResponse.locations:type_name -> location.Location
	0, // 1: location.LocationService.FindSuitableLocations:input_type -> location.FindLocationsRequest
	3, // 2: location.LocationService.GetLocationDetails:input_type -> location.GetLocationDetailsRequest
	2, // 3: location.LocationService.FindSuitableLocations:output_type -> location.FindLocationsResponse
	4, // 4: location.LocationService.GetLocationDetails:output_type -> location.LocationDetailsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_location_proto_init() }
func file_proto_location_proto_init() {
	if File_proto_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_location_proto_rawDesc), len(file_proto_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_location_proto_goTypes,
		DependencyIndexes: file_proto_location_proto_depIdxs,
		MessageInfos:      file_proto_location_proto_msgTypes,
	}.Build()
	File_proto_location_proto = out.File
	file_proto_location_proto_goTypes = nil
	file_proto_location_proto_depIdxs = nil
}
