// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/preference.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.

const (
	PreferenceService_GetPreferences_FullMethodName     = "/preference.PreferenceService/GetPreferences"
	PreferenceService_SavePreferences_FullMethodName    = "/preference.PreferenceService/SavePreferences"
	PreferenceService_GetUserPreferences_FullMethodName = "/preference.PreferenceService/GetUserPreferences"
)

// PreferenceServiceClient is the client API for PreferenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PreferenceServiceClient interface {
	GetPreferences(ctx context.Context, in *PreferenceRequest, opts ...grpc.CallOption) (*PreferenceResponse, error)
	SavePreferences(ctx context.Context, in *PreferenceRequest, opts ...grpc.CallOption) (*Empty, error)
	GetUserPreferences(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*PreferenceRequest, error)
}

type preferenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPreferenceServiceClient(cc grpc.ClientConnInterface) PreferenceServiceClient {
	return &preferenceServiceClient{cc}
}

func (c *preferenceServiceClient) GetPreferences(ctx context.Context, in *PreferenceRequest, opts ...grpc.CallOption) (*PreferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreferenceResponse)
	err := c.cc.Invoke(ctx, PreferenceService_GetPreferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *preferenceServiceClient) SavePreferences(ctx context.Context, in *PreferenceRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PreferenceService_SavePreferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *preferenceServiceClient) GetUserPreferences(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*PreferenceRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreferenceRequest)
	err := c.cc.Invoke(ctx, PreferenceService_GetUserPreferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PreferenceServiceServer is the server API for PreferenceService service.
// All implementations must embed UnimplementedPreferenceServiceServer
// for forward compatibility.
type PreferenceServiceServer interface {
	GetPreferences(context.Context, *PreferenceRequest) (*PreferenceResponse, error)
	SavePreferences(context.Context, *PreferenceRequest) (*Empty, error)
	GetUserPreferences(context.Context, *UserRequest) (*PreferenceRequest, error)
	mustEmbedUnimplementedPreferenceServiceServer()
}

// UnimplementedPreferenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPreferenceServiceServer struct{}

func (UnimplementedPreferenceServiceServer) GetPreferences(context.Context, *PreferenceRequest) (*PreferenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPreferences not implemented")
}
func (UnimplementedPreferenceServiceServer) SavePreferences(context.Context, *PreferenceRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SavePreferences not implemented")
}
func (UnimplementedPreferenceServiceServer) GetUserPreferences(context.Context, *UserRequest) (*PreferenceRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserPreferences not implemented")
}
func (UnimplementedPreferenceServiceServer) mustEmbedUnimplementedPreferenceServiceServer() {}
func (UnimplementedPreferenceServiceServer) testEmbeddedByValue()                           {}

// UnsafePreferenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PreferenceServiceServer will
// result in compilation errors.
type UnsafePreferenceServiceServer interface {
	mustEmbedUnimplementedPreferenceServiceServer()
}

func RegisterPreferenceServiceServer(s grpc.ServiceRegistrar, srv PreferenceServiceServer) {
	// If the following call panics, it indicates UnimplementedPreferenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PreferenceService_ServiceDesc, srv)
}

func _PreferenceService_GetPreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreferenceServiceServer).GetPreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreferenceService_GetPreferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreferenceServiceServer).GetPreferences(ctx, req.(*PreferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PreferenceService_SavePreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreferenceServiceServer).SavePreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreferenceService_SavePreferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreferenceServiceServer).SavePreferences(ctx, req.(*PreferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PreferenceService_GetUserPreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreferenceServiceServer).GetUserPreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreferenceService_GetUserPreferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreferenceServiceServer).GetUserPreferences(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PreferenceService_ServiceDesc is the grpc.ServiceDesc for PreferenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PreferenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "preference.PreferenceService",
	HandlerType: (*PreferenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPreferences",
			Handler:    _PreferenceService_GetPreferences_Handler,
		},
		{
			MethodName: "SavePreferences",
			Handler:    _PreferenceService_SavePreferences_Handler,
		},
		{
			MethodName: "GetUserPreferences",
			Handler:    _PreferenceService_GetUserPreferences_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/preference.proto",
}
