// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/preference.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mood          string                 `protobuf:"bytes,2,opt,name=mood,proto3" json:"mood,omitempty"`
	TimeOfDay     string                 `protobuf:"bytes,3,opt,name=time_of_day,json=timeOfDay,proto3" json:"time_of_day,omitempty"`
	Budget        string                 `protobuf:"bytes,4,opt,name=budget,proto3" json:"budget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreferenceRequest) Reset() {
	*x = PreferenceRequest{}
	mi := &file_proto_preference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreferenceRequest) ProtoMessage() {}

func (x *PreferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_preference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreferenceRequest.ProtoReflect.Descriptor instead.
func (*PreferenceRequest) Descriptor() ([]byte, []int) {
	return file_proto_preference_proto_rawDescGZIP(), []int{0}
}

func (x *PreferenceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PreferenceRequest) GetMood() string {
	if x != nil {
		return x.Mood
	}
	return ""
}

func (x *PreferenceRequest) GetTimeOfDay() string {
	if x != nil {
		return x.TimeOfDay
	}
	return ""
}

func (x *PreferenceRequest) GetBudget() string {
	if x != nil {
		return x.Budget
	}
	return ""
}

type PreferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []string               `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreferenceResponse) Reset() {
	*x = PreferenceResponse{}
	mi := &file_proto_preference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreferenceResponse) ProtoMessage() {}

func (x *PreferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_preference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreferenceResponse.ProtoReflect.Descriptor instead.
func (*PreferenceResponse) Descriptor() ([]byte, []int) {
	return file_proto_preference_proto_rawDescGZIP(), []int{1}
}

func (x *PreferenceResponse) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_proto_preference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_preference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_proto_preference_proto_rawDescGZIP(), []int{2}
}

func (x *UserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_preference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_preference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_preference_proto_rawDescGZIP(), []int{3}
}

var File_proto_preference_proto protoreflect.FileDescriptor

const file_proto_preference_proto_rawDesc = "" +
	"\n" +
	"\x16proto/preference.proto\x12\n" +
	"preference\"x\n" +
	"\x11PreferenceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04mood\x18\x02 \x01(\tR\x04mood\x12\x1e\n" +
	"\vtime_of_day\x18\x03 \x01(\tR\ttimeOfDay\x12\x16\n" +
	"\x06budget\x18\x04 \x01(\tR\x06budget\"4\n" +
	"\x12PreferenceResponse\x12\x1e\n" +
	"\n" +
	"categories\x18\x01 \x03(\tR\n" +
	"categories\"&\n" +
	"\vUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\a\n" +
	"\x05Empty2\xf7\x01\n" +
	"\x11PreferenceService\x12O\n" +
	"\x0eGetPreferences\x12\x1d.preference.PreferenceRequest\x1a\x1e.preference.PreferenceResponse\x12C\n" +
	"\x0fSavePreferences\x12\x1d.preference.PreferenceRequest\x1a\x11.preference.Empty\x12L\n" +
	"\x12GetUserPreferences\x12\x17.preference.UserRequest\x1a\x1d.preference.PreferenceRequestB\bZ\x06proto/b\x06proto3"

var (
	file_proto_preference_proto_rawDescOnce sync.Once
	file_proto_preference_proto_rawDescData []byte
)

func file_proto_preference_proto_rawDescGZIP() []byte {
	file_proto_preference_proto_rawDescOnce.Do(func() {
		file_proto_preference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_preference_proto_rawDesc), len(file_proto_preference_proto_rawDesc)))
	})
	return file_proto_preference_proto_rawDescData
}

var file_proto_preference_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_preference_proto_goTypes = []any{
	(*PreferenceRequest)(nil),  // 0: preference.PreferenceRequest
	(*PreferenceResponse)(nil), // 1: preference.PreferenceResponse
	(*UserRequest)(nil),        // 2: preference.UserRequest
	(*Empty)(nil),              // 3: preference.Empty
}
var file_proto_preference_proto_depIdxs = []int32{
	0, // 0: preference.PreferenceService.GetPreferences:input_type -> preference.PreferenceRequest
	0, // 1: preference.PreferenceService.SavePreferences:input_type -> preference.PreferenceRequest
	2, // 2: preference.PreferenceService.GetUserPreferences:input_type -> preference.UserRequest
	1, // 3: preference.PreferenceService.GetPreferences:output_type -> preference.PreferenceResponse
	3, // 4: preference.PreferenceService.SavePreferences:output_type -> preference.Empty
	0, // 5: preference.PreferenceService.GetUserPreferences:output_type -> preference.PreferenceRequest
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_preference_proto_init() }
func file_proto_preference_proto_init() {
	if File_proto_preference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_preference_proto_rawDesc), len(file_proto_preference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_preference_proto_goTypes,
		DependencyIndexes: file_proto_preference_proto_depIdxs,
		MessageInfos:      file_proto_preference_proto_msgTypes,
	}.Build()
	File_proto_preference_proto = out.File
	file_proto_preference_proto_goTypes = nil
	file_proto_preference_proto_depIdxs = nil
}
