// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/route-generation.proto

package routepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRouteByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteByIDRequest) Reset() {
	*x = GetRouteByIDRequest{}
	mi := &file_proto_route_generation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteByIDRequest) ProtoMessage() {}

func (x *GetRouteByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_generation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteByIDRequest.ProtoReflect.Descriptor instead.
func (*GetRouteByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_route_generation_proto_rawDescGZIP(), []int{0}
}

func (x *GetRouteByIDRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

type GetUserRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRoutesRequest) Reset() {
	*x = GetUserRoutesRequest{}
	mi := &file_proto_route_generation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRoutesRequest) ProtoMessage() {}

func (x *GetUserRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_generation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRoutesRequest.ProtoReflect.Descriptor instead.
func (*GetUserRoutesRequest) Descriptor() ([]byte, []int) {
	return file_proto_route_generation_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserRoutesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*Route               `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRoutesResponse) Reset() {
	*x = GetUserRoutesResponse{}
	mi := &file_proto_route_generation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRoutesResponse) ProtoMessage() {}

func (x *GetUserRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_generation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRoutesResponse.ProtoReflect.Descriptor instead.
func (*GetUserRoutesResponse) Descriptor() ([]byte, []int) {
	return file_proto_route_generation_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRoutesResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

type RouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *Route                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	mi := &file_proto_route_generation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_generation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_proto_route_generation_proto_rawDescGZIP(), []int{3}
}

func (x *RouteResponse) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PreferenceId  string                 `protobuf:"bytes,3,opt,name=preference_id,json=preferenceId,proto3" json:"preference_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Mood          string                 `protobuf:"bytes,5,opt,name=mood,proto3" json:"mood,omitempty"`
	City          string                 `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	TotalBudget   int32                  `protobuf:"varint,7,opt,name=total_budget,json=totalBudget,proto3" json:"total_budget,omitempty"`
	TotalDuration int32                  `protobuf:"varint,8,opt,name=total_duration,json=totalDuration,proto3" json:"total_duration,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Places        []*RoutePlace          `protobuf:"bytes,10,rep,name=places,proto3" json:"places,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_proto_route_generation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_generation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_proto_route_generation_proto_rawDescGZIP(), []int{4}
}

func (x *Route) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Route) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Route) GetPreferenceId() string {
	if x != nil {
		return x.PreferenceId
	}
	return ""
}

func (x *Route) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Route) GetMood() string {
	if x != nil {
		return x.Mood
	}
	return ""
}

func (x *Route) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Route) GetTotalBudget() int32 {
	if x != nil {
		return x.TotalBudget
	}
	return 0
}

func (x *Route) GetTotalDuration() int32 {
	if x != nil {
		return x.TotalDuration
	}
	return 0
}

func (x *Route) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Route) GetPlaces() []*RoutePlace {
	if x != nil {
		return x.Places
	}
	return nil
}

type RoutePlace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RouteId       string                 `protobuf:"bytes,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	PlaceId       string                 `protobuf:"bytes,3,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Lat           float64                `protobuf:"fixed64,7,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,8,opt,name=lon,proto3" json:"lon,omitempty"`
	VisitOrder    int32                  `protobuf:"varint,9,opt,name=visit_order,json=visitOrder,proto3" json:"visit_order,omitempty"`
	EstimatedTime int32                  `protobuf:"varint,10,opt,name=estimated_time,json=estimatedTime,proto3" json:"estimated_time,omitempty"`
	EstimatedCost int32                  `protobuf:"varint,11,opt,name=estimated_cost,json=estimatedCost,proto3" json:"estimated_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutePlace) Reset() {
	*x = RoutePlace{}
	mi := &file_proto_route_generation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutePlace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePlace) ProtoMessage() {}

func (x *RoutePlace) ProtoReflect() protoreflect.Message {
	mi := &file_proto_route_generation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePlace.ProtoReflect.Descriptor instead.
func (*RoutePlace) Descriptor() ([]byte, []int) {
	return file_proto_route_generation_proto_rawDescGZIP(), []int{5}
}

func (x *RoutePlace) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoutePlace) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *RoutePlace) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

func (x *RoutePlace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoutePlace) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RoutePlace) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RoutePlace) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *RoutePlace) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *RoutePlace) GetVisitOrder() int32 {
	if x != nil {
		return x.VisitOrder
	}
	return 0
}

func (x *RoutePlace) GetEstimatedTime() int32 {
	if x != nil {
		return x.EstimatedTime
	}
	return 0
}

func (x *RoutePlace) GetEstimatedCost() int32 {
	if x != nil {
		return x.EstimatedCost
	}
	return 0
}

var File_proto_route_generation_proto protoreflect.FileDescriptor

const file_proto_route_generation_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/route-generation.proto\x12\x05route\"0\n" +
	"\x13GetRouteByIDRequest\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\"/\n" +
	"\x14GetUserRoutesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"=\n" +
	"\x15GetUserRoutesResponse\x12$\n" +
	"\x06routes\x18\x01 \x03(\v2\f.route.RouteR\x06routes\"3\n" +
	"\rRouteResponse\x12\"\n" +
	"\x05route\x18\x01 \x01(\v2\f.route.RouteR\x05route\"\xa7\x02\n" +
	"\x05Route\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rpreference_id\x18\x03 \x01(\tR\fpreferenceId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04mood\x18\x05 \x01(\tR\x04mood\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\x12!\n" +
	"\ftotal_budget\x18\a \x01(\x05R\vtotalBudget\x12%\n" +
	"\x0etotal_duration\x18\b \x01(\x05R\rtotalDuration\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12)\n" +
	"\x06places\x18\n" +
	" \x03(\v2\x11.route.RoutePlaceR\x06places\"\xa7\x02\n" +
	"\n" +
	"RoutePlace\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\tR\arouteId\x12\x19\n" +
	"\bplace_id\x18\x03 \x01(\tR\aplaceId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x10\n" +
	"\x03lat\x18\a \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\b \x01(\x01R\x03lon\x12\x1f\n" +
	"\vvisit_order\x18\t \x01(\x05R\n" +
	"visitOrder\x12%\n" +
	"\x0eestimated_time\x18\n" +
	" \x01(\x05R\restimatedTime\x12%\n" +
	"\x0eestimated_cost\x18\v \x01(\x05R\restimatedCost2\x9c\x01\n" +
	"\fRouteService\x12@\n" +
	"\fGetRouteByID\x12\x1a.route.GetRouteByIDRequest\x1a\x14.route.RouteResponse\x12J\n" +
	"\rGetUserRoutes\x12\x1b.route.GetUserRoutesRequest\x1a\x1c.route.GetUserRoutesResponseB\x11Z\x0f./proto/routepbb\x06proto3"

var (
	file_proto_route_generation_proto_rawDescOnce sync.Once
	file_proto_route_generation_proto_rawDescData []byte
)

func file_proto_route_generation_proto_rawDescGZIP() []byte {
	file_proto_route_generation_proto_rawDescOnce.Do(func() {
		file_proto_route_generation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_route_generation_proto_rawDesc), len(file_proto_route_generation_proto_rawDesc)))
	})
	return file_proto_route_generation_proto_rawDescData
}

var file_proto_route_generation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_route_generation_proto_goTypes = []any{
	(*GetRouteByIDRequest)(nil),   // 0: route.GetRouteByIDRequest
	(*GetUserRoutesRequest)(nil),  // 1: route.GetUserRoutesRequest
	(*GetUserRoutesResponse)(nil), // 2: route.GetUserRoutesResponse
	(*RouteResponse)(nil),         // 3: route.RouteResponse
	(*Route)(nil),                 // 4: route.Route
	(*RoutePlace)(nil),            // 5: route.RoutePlace
}
var file_proto_route_generation_proto_depIdxs = []int32{
	4, // 0: route.GetUserRoutesResponse.routes:type_name -> route.Route
	4, // 1: route.RouteResponse.route:type_name -> route.Route
	5, // 2: route.Route.places:type_name -> route.RoutePlace
	0, // 3: route.RouteService.GetRouteByID:input_type -> route.GetRouteByIDRequest
	1, // 4: route.RouteService.GetUserRoutes:input_type -> route.GetUserRoutesRequest
	3, // 5: route.RouteService.GetRouteByID:output_type -> route.RouteResponse
	2, // 6: route.RouteService.GetUserRoutes:output_type -> route.GetUserRoutesResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_route_generation_proto_init() }
func file_proto_route_generation_proto_init() {
	if File_proto_route_generation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_route_generation_proto_rawDesc), len(file_proto_route_generation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_route_generation_proto_goTypes,
		DependencyIndexes: file_proto_route_generation_proto_depIdxs,
		MessageInfos:      file_proto_route_generation_proto_msgTypes,
	}.Build()
	File_proto_route_generation_proto = out.File
	file_proto_route_generation_proto_goTypes = nil
	file_proto_route_generation_proto_depIdxs = nil
}
